### ISSUE TITLE
Hovery

### ISSUE THREAD

**Issue by mariuszstroz** [poulch/Blog#6]
Niech na linkach `<a>` (tutuł przycisk) będzie jakiś efekt po najechaniu. Niech kolor zmienia się delikatnie na ciemniejszy

Niech efekt będzie płynnt (css transition)
Nadać transition na górne menu.

![2016-04-06_1257](https://cloud.githubusercontent.com/assets/771899/14314444/7b027622-fbf7-11e5-94ea-43d3ed189e11.png)

**Comment by mariuszstroz** [comment]
Tak samo hover na kategoriach w prawym menu

**Comment by poulch** [comment]
hover post info:

a{
              display: inline-block;
              background: black;
              padding: 0;
              height: 263px;

              img{
                transition: all .3s ease;
                display: block;
                width: 100%;
                height: 100%;
              }

              &:hover{
                img{
                  opacity: 0.7;
                }
              }
            }

**Comment by mariuszstroz** [comment]
Zróbmy to dla pewności za pomocą css3generator

Warto zrobić do tego MIXIN w sass by nie powtarzać tego wszędzie i by łatwo zmienić np czas animacji później

![2016-04-07_1121](https://cloud.githubusercontent.com/assets/771899/14346513/e0727e92-fcb2-11e5-85fe-36abda583f41.png)
